AppEntry: use clear-all icon and add tooltip
elementary/wingpanel-indicator-notifications pull request #137
Opened 2020-09-26 01:20 UTC by danrabbit

As suggested in #136 

![Screenshot from 2020-09-25 18 19 00@2x](https://user-images.githubusercontent.com/7277719/94326845-bf9bff80-ff5b-11ea-8545-4a4185837a16.png)

2020-09-26 06:30 UTC, ryonakano requested changes

2020-09-26 06:30 UTC, ryonakano commented on src/Widgets/AppEntry.vala
> +            tooltip_text = _("Clear all %s notifications".printf (app_info.get_name ()))
```suggestion
            tooltip_text = _("Clear all %s notifications").printf (app_info.get_name ())
```

I guess the current code does not make the string translatable

2020-09-26 11:53 UTC, hanaral commented
ngl I had to look at it twice to realise it was a broom and not a brush. Could the symbolic icon itself be updated to look more like a broom?

2020-09-28 18:11 UTC, danrabbit commented
@hanaral that's outside the scope of this repo. Can you open a new issue report against github.com/elementary/icons

2020-09-28 23:16 UTC, ryonakano approved these changes

2020-09-28 23:31 UTC, merged