Changed the logic for handling notifications with no body (The title …
elementary/wingpanel-indicator-notifications pull request #222
Opened 2021-09-08 07:40 UTC by lorencinibrdev

…and application name are used)

Should fix #219.

2021-09-08 07:49 UTC, lorencinibrdev commented
Attaching screenshot:

![image](https://user-images.githubusercontent.com/4778177/132468567-b0a6884b-ae80-47ce-926f-382840b61259.png)

2021-09-08 16:50 UTC, cassidyjames submitted a review, later dismissed
Couple of whitespace issues

2021-09-08 16:50 UTC, cassidyjames commented on src/Widgets/NotificationEntry.vala
> +
Whitespace is failing lint

```suggestion

        var entry_title = notification.summary;

```

2021-09-08 16:50 UTC, cassidyjames commented on src/Widgets/NotificationEntry.vala
> +
Whitespace lint here as well

```suggestion

        if (entry_body == "") {
            entry_body = notification.summary;
        }

```

2021-09-08 17:41 UTC, lorencinibrdev commented
Thanks again for the review @cassidyjames. I'm sorry for the trouble.

Is there any way to have these checks tests done before doing a PR?

2021-09-08 18:27 UTC, danrabbit requested changes
One more small thing! It looks like `app_name` is guaranteed to be set. If we get valid AppInfo in `notification` we should make sure to set `app_name` there

And yes you could install an run vala-lint ahead of time if you like :)

2021-09-18 05:07 UTC, lorencinibrdev commented
Hi @danrabbit , thanks for the tip on vala-lint. Worked fine here.

Could you please clarify what you meant about the PR? I checked here, like you said, seems like app_name is indeed always set on Notification class.

2021-09-18 05:10 UTC, danrabbit commented
Sorry I meant to say that it *isnt* guaranteed that `app_name` is set.

If we have valid appinfo, we should make sure to set `app_name` based on that appinfo

2021-09-18 05:37 UTC, lorencinibrdev commented
Think i got it now. Thanks for the help! Let me know if any change is necessary.

2021-09-18 05:44 UTC, lorencinibrdev commented
Adding a image as evidence.

![ScreenShot](https://user-images.githubusercontent.com/4778177/133877532-b48ea2ef-f60a-45c8-9f5d-4f1b24bdeee1.png)

2021-09-20 17:15 UTC, danrabbit approved these changes
Working as expected, thanks for the fix!

2021-09-20 17:16 UTC, merged